import { Bookings } from "../bookings/bookings.entity";
import { Locations } from "../locations/locations.entity";
import { Users } from "../users/users.entity";
import { Column, Entity, ManyToOne, OneToMany, PrimaryGeneratedColumn } from "typeorm";

/**
 * Slots entity class
 */
@Entity()
export class Slots {

  /**
   * @type : number
   * primary key and its auto generated by database
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * @type:string
   * accepts the string value
   */
  @Column()
  startTime: string;

  /**
   * @type:number
   * accepts the number value
   */
  @Column()
  endTime: string;

  /**
   * @type:string
   * accepts the string value
   */
  @Column({ default: 'Available' })
  status: string

  /**
   * @type:string
   * accepts the string value
   */
  @Column()
  hospital: string;

  /**
   * Relation between user and books
   */
  @ManyToOne(() => Users, (users) => users.slots)
  users: Users;

  /**
   * Relation between slots and locations
   */
  @ManyToOne(() => Locations, (locations) => locations.slots)
  locations: Locations

  /**
   * Relation between booking
   */
  @OneToMany(() => Bookings, (bookings) => bookings.slots)
  bookings: Bookings[];
}